main: main.cc main.h strings/strings.h strings/strings1.cc strings/strings2.cc strings/addstring1.cc strings/addstring2.cc strings/size.cc strings/at1.cc strings/at2.cc
	g++ -std=c++11 -Wall -o main main.cc strings/strings1.cc strings/strings2.cc strings/addstring1.cc strings/addstring2.cc strings/size.cc strings/at1.cc strings/at2.cc
